# Generated by Django 5.0 on 2023-12-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewApp", "0002_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="stu_id",
            field=models.IntegerField(default=278),
        ),
    ]
