# Generated by Django 5.0 on 2023-12-23 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NewApp", "0003_data_stu_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="stu_id",
            new_name="stu_reg",
        ),
    ]
